-- Superstore Sales Analysis Queries

-- 1. Region-wise Sales and Profit
SELECT
    REGION,
    SUM(SALES) AS TOTAL_SALES,
    SUM(PROFIT) AS TOTAL_PROFIT
FROM METRICMIND_DB.PUBLIC.SUPERSTORE_CLEAN
GROUP BY REGION
ORDER BY TOTAL_SALES DESC;


-- 2. Segment-wise Sales and Profit
SELECT
    SEGMENT,
    SUM(SALES) AS TOTAL_SALES,
    SUM(PROFIT) AS TOTAL_PROFIT
FROM METRICMIND_DB.PUBLIC.SUPERSTORE_CLEAN
GROUP BY SEGMENT
ORDER BY TOTAL_SALES DESC;


-- 3. Ship Mode Performance
SELECT
    SHIP_MODE,
    COUNT(*) AS TOTAL_ORDERS,
    SUM(SALES) AS TOTAL_SALES,
    SUM(PROFIT) AS TOTAL_PROFIT
FROM METRICMIND_DB.PUBLIC.SUPERSTORE_CLEAN
GROUP BY SHIP_MODE
ORDER BY TOTAL_SALES DESC;


-- 4. Top 10 Customers by Sales
SELECT
    CUSTOMER_NAME,
    SUM(SALES) AS TOTAL_SALES,
    SUM(PROFIT) AS TOTAL_PROFIT
FROM METRICMIND_DB.PUBLIC.SUPERSTORE_CLEAN
GROUP BY CUSTOMER_NAME
ORDER BY TOTAL_SALES DESC
LIMIT 10;


-- 5. Top 10 Products by Sales
SELECT
    PRODUCT_ID,
    SUM(SALES) AS TOTAL_SALES,
    SUM(PROFIT) AS TOTAL_PROFIT
FROM METRICMIND_DB.PUBLIC.SUPERSTORE_CLEAN
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC
LIMIT 10;


-- 6. Year-wise Sales and Profit
SELECT
    YEAR(TO_DATE(ORDER_DATE)) AS ORDER_YEAR,
    SUM(SALES) AS TOTAL_SALES,
    SUM(PROFIT) AS TOTAL_PROFIT
FROM METRICMIND_DB.PUBLIC.SUPERSTORE_CLEAN
GROUP BY YEAR(TO_DATE(ORDER_DATE))
ORDER BY ORDER_YEAR;


-- 7. Loss-Making Products
SELECT
    PRODUCT_ID,
    SUM(SALES) AS TOTAL_SALES,
    SUM(PROFIT) AS TOTAL_PROFIT
FROM METRICMIND_DB.PUBLIC.SUPERSTORE_CLEAN
GROUP BY PRODUCT_ID
HAVING SUM(PROFIT) < 0
ORDER BY TOTAL_PROFIT ASC
LIMIT 10;


-- 8. Top 10 Profitable Products
SELECT
    PRODUCT_ID,
    SUM(SALES) AS TOTAL_SALES,
    SUM(PROFIT) AS TOTAL_PROFIT
FROM METRICMIND_DB.PUBLIC.SUPERSTORE_CLEAN
GROUP BY PRODUCT_ID
ORDER BY TOTAL_PROFIT DESC
LIMIT 10;


-- 9. State-wise Sales and Profit
SELECT
    STATE,
    SUM(SALES) AS TOTAL_SALES,
    SUM(PROFIT) AS TOTAL_PROFIT
FROM METRICMIND_DB.PUBLIC.SUPERSTORE_CLEAN
GROUP BY STATE
ORDER BY TOTAL_SALES DESC;


-- 10. Final KPI Summary
SELECT
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
    COUNT(DISTINCT CUSTOMER_ID) AS TOTAL_CUSTOMERS,
    SUM(SALES) AS TOTAL_SALES,
    SUM(PROFIT) AS TOTAL_PROFIT,
    AVG(DISCOUNT) AS AVERAGE_DISCOUNT,
    SUM(QUANTITY) AS TOTAL_QUANTITY
FROM METRICMIND_DB.PUBLIC.SUPERSTORE_CLEAN;
